// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvdwbuguajkpzjwlekoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZHdidWd1YWprcHpqd2xla29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMDkyMTQsImV4cCI6MjA1MjU4NTIxNH0.To3va5JszD2_lqJ6LfsEPXydwaFmA46Ef37168AtVu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);